port=8443
cert=cert.pem
key=key.pem
threads=80
max_request_size=12400
log_file=server.log
cgi_dir=cgi

enable_chroot=0
chroot_dir=.
user=nobody

cors_enabled=1
cors_allow_origin=*
cors_allow_methods=GET, POST, OPTIONS
cors_allow_headers=Content-Type
error_404_page=www/errors/404.html
logging_ratelimit=100
logging_time_window=60
cgi_ext=
